name: mirem
favicon: null
layout_spectrum: 0.5194868091493845
typography_spectrum: 0.5946651739068329
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6872671854216605
  lightness: 0.38673860509879887
  saturation: 0.0032556108199059963
  rhythmicContrast: 0.7061052634380758
purpose: []
